# vim ft=yaml
# Multiple lines can be made a single "virtual line" because of how Travis
# munges each line before executing it to print out the exit status.  It's okay
# for it to be on multiple physical lines, so long as you remember: - There
# can't be any leading "-"s - All newlines will be removed, so use ";"s

language: python

python:
    - 2.6
    - 3.2
    - 3.3
    - 3.4

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=--with-coverage
    - python: 3.4
      env:
        - DEPS=minimal

before_install:
    # pydicom <= 0.9.8 doesn't install on python 3
    - if [[ "${TRAVIS_PYTHON_VERSION:0:1}" < "3" ]]; then
      pip install pydicom;
      fi
    - if [ "${COVERAGE}" == "--with-coverage" ]; then
      pip install coverage;
      pip install coveralls;
      fi
    # Create a (fake) display on Travis so that mpl tests work
    # TODO: Could also use the `agg` backend instead
    - if [ "${DEPS}" != "minimal" ]; then
      pip install matplotlib;
      export DISPLAY=:99.0;
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
      fi;

install:
    - python setup.py install

script:
    # Change into an innocuous directory and find tests from installation
    - mkdir for_testing
    - cd for_testing
    - if [ "${COVERAGE}" == "--with-coverage" ]; then cp ../.coveragerc .; fi
    - nosetests --with-doctest $COVERAGE `python -c "import os; import nibabel; print(os.path.dirname(nibabel.__file__))"`

after_success:
    - if [ "${COVERAGE}" == "--with-coverage" ]; then coveralls; fi
